name: Check Markdown Links

on: 
  push:
    branches: [ "main" ]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@1
      with:
        config-file: 'mlc_config.json'
